"""esquema inicial: todas las tablas del dominio

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-08 22:03:47.813726

"""
from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depositos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rematadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('matricula', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('doc_frente_url', sa.String(length=500), nullable=True),
    sa.Column('doc_dorso_url', sa.String(length=500), nullable=True),
    sa.Column('domicilio', sa.String(length=250), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.Enum('COMUN', 'ESPECIAL', 'PLATA', 'ORO', 'PLATINO', name='categoriausuario'), nullable=False),
    sa.Column('estado_registro', sa.Enum('PENDIENTE_VERIFICACION', 'APROBADO_FASE_1', 'COMPLETO', 'RECHAZADO', 'BLOQUEADO', name='estadoregistro'), nullable=False),
    sa.Column('bloqueado_por_impago', sa.Boolean(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_pieza', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('dueno_actual_id', sa.Integer(), nullable=True),
    sa.Column('artista', sa.String(length=160), nullable=True),
    sa.Column('fecha_obra', sa.String(length=40), nullable=True),
    sa.Column('historia', sa.Text(), nullable=True),
    sa.Column('cantidad_elementos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'EN_SUBASTA', 'VENDIDO', 'RETIRADO', name='estadoarticulo'), nullable=False),
    sa.Column('deposito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deposito_id'], ['depositos.id'], ),
    sa.ForeignKeyConstraint(['dueno_actual_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articulos_numero_pieza'), ['numero_pieza'], unique=True)

    op.create_table('cuentas_cobro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('banco', sa.String(length=120), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=60), nullable=False),
    sa.Column('titular', sa.String(length=160), nullable=False),
    sa.Column('declarada_antes_subasta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medios_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CUENTA_BANCARIA', 'TARJETA_CREDITO', 'CHEQUE_CERTIFICADO', name='tipomediopago'), nullable=False),
    sa.Column('titular', sa.String(length=160), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=False),
    sa.Column('monto_garantia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'VERIFICADO', 'RECHAZADO', name='estadomediopago'), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('seguros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_poliza', sa.String(length=60), nullable=False),
    sa.Column('compania', sa.String(length=120), nullable=False),
    sa.Column('beneficiario_id', sa.Integer(), nullable=False),
    sa.Column('monto_cubierto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_poliza')
    )
    op.create_table('solicitudes_subasta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('datos_historicos', sa.Text(), nullable=True),
    sa.Column('declara_propiedad', sa.Boolean(), nullable=False),
    sa.Column('origen_licito_acreditado', sa.Boolean(), nullable=False),
    sa.Column('revisar_origen', sa.Boolean(), nullable=False),
    sa.Column('acepta_devolucion_con_cargo', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('INGRESADA', 'EN_INSPECCION', 'ACEPTADA', 'RECHAZADA', 'CONFIRMADA_POR_USUARIO', 'RECHAZADA_POR_USUARIO', 'DEVUELTA', name='estadosolicitud'), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('precio_base_propuesto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('comision_propuesta', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fecha_subasta_propuesta', sa.DateTime(), nullable=True),
    sa.Column('respuesta_usuario', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subastas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('ubicacion', sa.String(length=250), nullable=False),
    sa.Column('categoria_minima', sa.Enum('COMUN', 'ESPECIAL', 'PLATA', 'ORO', 'PLATINO', name='categoriausuario'), nullable=False),
    sa.Column('moneda', sa.Enum('ARS', 'USD', name='moneda'), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'ABIERTA', 'CERRADA', 'CANCELADA', name='estadosubasta'), nullable=False),
    sa.Column('rematador_id', sa.Integer(), nullable=False),
    sa.Column('es_coleccion', sa.Boolean(), nullable=False),
    sa.Column('nombre_coleccion', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['rematador_id'], ['rematadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subasta_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('vendido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['subasta_id'], ['subastas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subasta_id', 'articulo_id')
    )
    op.create_table('imagenes_articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes_solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_subasta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguros_articulos',
    sa.Column('seguro_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['seguro_id'], ['seguros.id'], ),
    sa.PrimaryKeyConstraint('seguro_id', 'articulo_id')
    )
    op.create_table('pujas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subasta_id', sa.Integer(), nullable=False),
    sa.Column('catalogo_item_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADA', 'RECHAZADA', name='estadopuja'), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_item_id'], ['catalogo_items.id'], ),
    sa.ForeignKeyConstraint(['subasta_id'], ['subastas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pujas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pujas_fecha_hora'), ['fecha_hora'], unique=False)

    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalogo_item_id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('medio_pago_id', sa.Integer(), nullable=True),
    sa.Column('monto_final', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comision', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('retira_personalmente', sa.Boolean(), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('pagada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_item_id'], ['catalogo_items.id'], ),
    sa.ForeignKeyConstraint(['comprador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['medio_pago_id'], ['medios_pago.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalogo_item_id')
    )
    op.create_table('multas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('motivo', sa.String(length=250), nullable=False),
    sa.Column('pagada', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('derivada_justicia', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multas')
    op.drop_table('ventas')
    with op.batch_alter_table('pujas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pujas_fecha_hora'))

    op.drop_table('pujas')
    op.drop_table('seguros_articulos')
    op.drop_table('imagenes_solicitud')
    op.drop_table('imagenes_articulo')
    op.drop_table('catalogo_items')
    op.drop_table('subastas')
    op.drop_table('solicitudes_subasta')
    op.drop_table('seguros')
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_usuario_id'))

    op.drop_table('notificaciones')
    op.drop_table('medios_pago')
    op.drop_table('cuentas_cobro')
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articulos_numero_pieza'))

    op.drop_table('articulos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('rematadores')
    op.drop_table('depositos')
    # ### end Alembic commands ###
