"""medio_pago_fecha_creacion

Revision ID: 69be1fd6a81a
Revises: 0001_initial
Create Date: 2026-06-10 20:26:38.951178

"""
from alembic import op
import sqlalchemy as sa


revision = '69be1fd6a81a'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medios_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False, server_default=sa.text("(datetime('now'))")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medios_pago', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
